#!/usr/bin/env bash

backup="${HOME}/config.orig"

function link_dotfile {
	src=${1}
	dst=${2}

	mv ${HOME}/${dst} ${backup}/${dst}
	ln -s ${PWD}/${src} ${HOME}/${dst}
}

if [ ! -e ${backup} ]; then
	mkdir ${backup}
fi

for f in \
	.profile \
	.zshrc \
	.termcap \
	.tmux.conf \
	.emacs.d \
do

	link_dotfile ${f} ${f}

done

case $OSTYPE in
	darwin*)

		;;

	freebsd*)

		;;

	linux*)
		;;

	*)
		;;
esac

mv ~/.gitignore ${backup}/.gitignore.orig
ln -s ${PWD}/global.gitignore ~/.gitignore
mv ~/.gitconfig ${backup}/.gitconfig.orig
ln -s ${PWD}/global.gitconfig ~/.gitconfig

echo "
.ssh \
.gnupg \
is not linked.

INSTALL:
	zsh
	keychain
	emacs
	tmux
"
